"""Register one bounded real-provider mechanism experiment before execution.

This registers and prints an id. It never starts model work. Reusing the file
returns the original registration instead of creating another attempt.
"""
import argparse
import json
from pathlib import Path

from nexgent.evolution.controller import StudyController
from nexgent.kernel.programs import digest


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    args = parser.parse_args()
    root = args.root.resolve()
    path = root / "docs/research/registered-framework-mechanism-20260916.json"
    if path.exists():
        print(json.dumps({"registration": str(path), "study_id": json.loads(path.read_text(encoding="utf-8"))["study_id"], "new_registration": False}))
        return
    controller = StudyController(root)
    state = controller.create(
        "Investigate whether actual offspring evidence can improve the executable research program. "
        "Use the supplied benchmark only as the task environment. Diagnose registered public failures, "
        "change substantive improve control flow or agent coordination when justified, test actual "
        "offspring from the same task start, and let the inherited improver execute in the next generation. "
        "Keep task performance, measured meta utility and source execution as separate claims.",
        generations=2, arm="full", seed=43,
        budget={"max_model_calls": 36, "max_completion_tokens": 180000},
        prior_study="study-35d3b448578f4824", benchmark_id="scientific_discovery")
    registration = {
        "schema": "nexgent-framework-mechanism-registration-v1", "version": "0.8.0",
        "study_id": state["id"], "registered_at": state["created"],
        "question": state["question"], "benchmark_id": state["benchmark"]["id"],
        "seed": state["seed"], "generations": state["max_generations"], "arm": state["arm"],
        "budget": state["budget"], "initial_program": state["initial_program"],
        "initial_source_digest": controller.get_program(state["initial_program"])["digest"],
        "implementation_digest": state["implementation_digest"],
        "evaluator_digest": state["evaluator_digest"],
        "model_configuration_digest": digest(state["model_configuration"]),
        "models": sorted({p["model"] for p in state["model_configuration"]["profiles"].values()}),
        "prior": state["prior_research"],
        "hypothesis": "Actual development offspring feedback supports source-level revisions to an improver that can be inherited and compared independently.",
        "primary_mechanism_checks": [
            "A changed executable meta program is generated by the model and stored with source identity.",
            "The next outer generation actually executes an inherited changed improve program.",
            "The development probe actually executes both source improvers on a common task start, with equal arm caps.",
            "Probe feedback enters a subsequent source decision; repaired unmeasured source remains unverified."
        ],
        "independent_evaluation": {
            "condition": "Run once only if the completed study has evaluated descendants and a different executable research improver; otherwise record not applicable without paid same-program sampling.",
            "scientific_discovery": {"seeds": [491, 592], "k": 1},
            "bbh": {"seeds": [693], "k": 1, "purpose": "Cross-benchmark execution and portability; the strong baseline is saturated, so this is not evidence of unsolved-task gains."},
            "generation_budget": {"max_model_calls": 6, "max_completion_tokens": 30000, "max_development_experiments": 3},
            "arm_budget": {"max_model_calls": 6, "max_completion_tokens": 30000},
            "primary_effect": "Paired initial/evolved improvement_at_1 on meta_transfer after development-only selection; report every seed and missing outcome.",
            "analysis": "Small mechanism pilot, not a powered superiority claim. No optional stopping or new seed search based on results."
        },
        "falsification": [
            "No executable improver changes, no actual inherited execution, or an incomplete paired probe fails the respective mechanism check.",
            "Nonpositive independent paired effect does not support improved improver utility.",
            "Missing execution or costs cannot be replaced by zero or claimed as success."
        ],
        "scope": "Framework-level source evolution; scientific discovery and BBH are independent benchmark plugins. Prior scientific batch and confirmation remain immutable and are not rerun.",
        "stop_rule": "One two-generation attempt plus the predeclared conditional independent comparisons, within each frozen budget. Preserve errors and negative results; no automatic paid retry."
    }
    registration["registration_digest"] = digest(registration)
    path.write_text(json.dumps(registration, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"registration": str(path), "study_id": state["id"], "registration_digest": registration["registration_digest"], "new_registration": True}))


if __name__ == "__main__":
    main()
